"""
Report Generator Module
Generates structured audit reports in multiple formats.
"""

import json
from datetime import datetime
from typing import Dict, Any, List


class ReportGenerator:
    """Generates audit reports in JSON, HTML, and summary formats."""

    def generate_html_report(self, report: Dict[str, Any]) -> str:
        """Generate an HTML audit report."""
        findings = report.get("findings", [])
        risk_summary = report.get("risk_summary", {})

        severity_colors = {
            "Critical": "#dc3545",
            "High": "#fd7e14",
            "Medium": "#ffc107",
            "Low": "#28a745",
            "Informational": "#17a2b8",
        }

        findings_html = ""
        for i, finding in enumerate(findings, 1):
            severity = finding.get("severity", "Medium")
            color = severity_colors.get(severity, "#6c757d")
            explanation = finding.get("explanation", {})

            findings_html += f"""
            <div class="finding" style="border-left: 4px solid {color}; padding: 15px; margin: 10px 0; background: #f8f9fa;">
                <h3>#{i} {finding.get('vulnerability_type', 'Unknown')}
                    <span style="background: {color}; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px;">
                        {severity}
                    </span>
                </h3>
                <p><strong>Rule:</strong> {finding.get('rule_id', 'N/A')}</p>
                <p><strong>Description:</strong> {finding.get('description', '')}</p>
                <p><strong>Confidence:</strong> {finding.get('confidence', 0) * 100:.1f}%</p>
                {"<p><strong>Line:</strong> " + str(finding.get('line_number', '')) + "</p>" if finding.get('line_number') else ""}
                {"<pre><code>" + finding.get('line_content', '') + "</code></pre>" if finding.get('line_content') else ""}
                <p><strong>Remediation:</strong> {finding.get('remediation', '')}</p>
                {self._render_explanation_html(explanation)}
            </div>
            """

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Smart Contract Audit Report - {report.get('contract_name', 'Unknown')}</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1a1a2e; }}
        .summary {{ background: #e8f4f8; padding: 20px; border-radius: 8px; margin: 20px 0; }}
        .finding {{ border-radius: 4px; }}
        pre {{ background: #282c34; color: #abb2bf; padding: 10px; border-radius: 4px; overflow-x: auto; }}
        .stats {{ display: flex; gap: 20px; flex-wrap: wrap; }}
        .stat {{ background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }}
    </style>
</head>
<body>
    <h1>Smart Contract Audit Report</h1>
    <p><strong>Contract:</strong> {report.get('contract_name', 'Unknown')}</p>
    <p><strong>Date:</strong> {report.get('timestamp', datetime.utcnow().isoformat())}</p>
    <p><strong>Report ID:</strong> {report.get('id', 'N/A')}</p>

    <div class="summary">
        <h2>Risk Summary</h2>
        <p><strong>Overall Risk:</strong> {risk_summary.get('overall_risk', 'Unknown')}</p>
        <p><strong>Risk Score:</strong> {risk_summary.get('risk_score', 0)}/100</p>
        <p>{risk_summary.get('summary', '')}</p>
        <p><em>{risk_summary.get('recommendation', '')}</em></p>

        <div class="stats">
            <div class="stat"><h3 style="color: #dc3545;">{report.get('critical', 0)}</h3>Critical</div>
            <div class="stat"><h3 style="color: #fd7e14;">{report.get('high', 0)}</h3>High</div>
            <div class="stat"><h3 style="color: #ffc107;">{report.get('medium', 0)}</h3>Medium</div>
            <div class="stat"><h3 style="color: #28a745;">{report.get('low', 0)}</h3>Low</div>
            <div class="stat"><h3 style="color: #17a2b8;">{report.get('informational', 0)}</h3>Info</div>
        </div>
    </div>

    <h2>Detailed Findings</h2>
    {findings_html}

    <hr>
    <p><em>Generated by Smart Contract Auditor v1.0.0</em></p>
</body>
</html>"""
        return html

    def _render_explanation_html(self, explanation: Dict) -> str:
        """Render explanation section in HTML."""
        if not explanation:
            return ""

        html = '<details><summary><strong>Detailed Explanation</strong></summary>'

        if explanation.get("summary"):
            html += f'<p>{explanation["summary"]}</p>'

        if explanation.get("attack_scenario"):
            html += f'<h4>Attack Scenario</h4><pre>{explanation["attack_scenario"]}</pre>'

        if explanation.get("fix_example"):
            html += f'<h4>Fix Example</h4><pre><code>{explanation["fix_example"]}</code></pre>'

        if (explanation.get("code_context") or {}).get("code_snippet"):
            html += f'<h4>Code Context</h4><pre>{explanation["code_context"]["code_snippet"]}</pre>'

        html += '</details>'
        return html

    def generate_summary(self, report: Dict[str, Any]) -> str:
        """Generate a text summary of the report."""
        risk = report.get("risk_summary", {})
        lines = [
            f"=== Smart Contract Audit Summary ===",
            f"Contract: {report.get('contract_name', 'Unknown')}",
            f"Date: {report.get('timestamp', 'Unknown')}",
            f"Overall Risk: {risk.get('overall_risk', 'Unknown')} ({risk.get('risk_score', 0)}/100)",
            f"Total Issues: {report.get('total_issues', 0)}",
            f"  Critical: {report.get('critical', 0)}",
            f"  High: {report.get('high', 0)}",
            f"  Medium: {report.get('medium', 0)}",
            f"  Low: {report.get('low', 0)}",
            f"  Informational: {report.get('informational', 0)}",
            "",
            f"Recommendation: {risk.get('recommendation', 'N/A')}",
        ]
        return "\n".join(lines)
